version: '3.7'
name: prueba
services:
  api:
    environment:
      - NODE_ENV=production
    build:
      context: ./
      dockerfile: apps/api/Dockerfile
    ports:
      - '3000:3000'
  client:
    environment:
      - NODE_ENV=production
    build:
      context: ./
      dockerfile: apps/client/Dockerfile
    ports:
      - '8000:8000'
